---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anythingllm
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: anythingllm-kube-rbac-proxy
  port:
    targetPort: 8443
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
