---
apiVersion: v1
kind: Service
metadata:
  name: anythingllm-direct
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: anythingllm
  ports:
    - name: http
      port: 8888
      targetPort: 8888
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anythingllm
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: anythingllm-direct
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
