apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:    
    opendatahub.io/accelerator-name: ""
    opendatahub.io/apiProtocol: REST
    opendatahub.io/runtime-version: v0.18.0
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/recommended-accelerators: ""
    opendatahub.io/template-display-name: vLLM CPU (x86) ServingRuntime for KServe
    opendatahub.io/template-name: vllm-cpu
    openshift.io/display-name: vLLM CPU (x86) ServingRuntime for KServe
  name: vllm-cpu
  labels:
    opendatahub.io/dashboard: "true"
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  containers:
    - args:
        - --model
        - /mnt/models
        - --port
        - "8080"
        - --max-model-len
        - {{ .Values.model.maxModelLen | quote }}
        - '--served-model-name'
        - {{ .Values.model.name }}
        - '--enable-auto-tool-choice'
        - '--tool-call-parser'
        - 'hermes'
      image: {{ .Values.images.vllmRuntime }}
      name: kserve-container
      env:
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "2"
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
