---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    helm.sh/resource-policy: keep
    openshift.io/description: ''
    openshift.io/display-name: AnythingLLM
  name: anythingllm
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.storageClassName }}
  volumeMode: Filesystem
